structure:
    backbone:
        type: inv3_version2
        pretrained:
    spatial_encoding: true
    crop_h: 7
    crop_w: 7
    acy_head:
        type: global_sttr
        token_num: 16
        token_feature_dim: 512
        token_inchannel: 768
        embed_channel: 256
        Nhead: 8
        dropout_porb: 0.1
        num_encoder_layers: 2
    flow_head:
        type: global_sttr
        token_num: 16
        token_feature_dim: 512
        token_inchannel: 256
        embed_channel: 256
        Nhead: 8
        dropout_porb: 0.1
        num_encoder_layers: 2
    flow_backbone:
        type: i3d_flow_acy
        pretrained:
        in_channel: 832
        out_channel: 256
        cat: False
        OH: 87
        OW: 157
    head:
        type: st_plus_tr_cross_cluster_v2
        num_encoder_layers: 1
        num_decoder_layers: 1
        num_STTR_layers: 2
        total_size:
            training: 12
            val: 12
        window_size: 3
        Nhead: 8
        dropout_porb: 0.1
        embed_features: 512
        actions_num_classes: 9
        activities_num_classes: 8
    pose_head:
        type: st_plus_tr_cross_cluster_v2
        num_encoder_layers: 1
        num_decoder_layers: 1
        num_STTR_layers: 2
        total_size:
            training: 12
            val: 12
        window_size: 3
        Nhead: 8
        dropout_porb: 0.1
        input_features: 12544 #256*7*7
        embed_features: 256
        actions_num_classes: 9
        activities_num_classes: 8
dataset:
    img_h: 720
    img_w: 1280
    workers: 2
    train:
        sample: 'train'
        batch_size: 2
        flip: true
        data_path: 'path_to/volleyball/videos' # include flow
        tracks: 'path_to/videos/tracks_normalized.pkl'
        keypoints: 'path_to/volleyball_result_kpt.json'
        seqs: [1,3,6,7,10,13,15,16,18,22,23,31,32,36,38,39,40,41,42,48,50,52,53,54,0,2,8,12,17,19,24,26,27,28,30,33,46,49,51]
    val:
        sample: 'val'
        batch_size: 1
        flip: false
        data_path: 'path_to/volleyball/videos' # include flow
        tracks: 'path_to/videos/tracks_normalized.pkl'
        keypoints: 'path_to/volleyball_result_kpt.json'
        seqs: [4,5,9,11,14,20,21,25,29,34,35,37,43,44,45,47]
train:
    start_epoch: 0
    criterion: ce_loss
    actions_weight: [1., 1., 2., 3., 1., 2., 2., 0.2, 1.]
    activities_weight: [1., 1., 1., 1., 1., 1., 1., 1.]
    scheduler:
        epochs: 150
        milestones: [50,100]
        gamma: 0.1
    optimizer:
        type: Adam
        kwargs:
            lr: 0.0001
            #momentum: 0.9
    print_freq: 50
    resume:
    pretrain: null
common:
    means: [0.485,0.456,0.406]
    stds: [0.229,0.224,0.225]
    seed: 100
